### ISSUE TITLE
мстители почти финал

### ISSUE THREAD

**Issue by GandhiKK** [GandhiKK/CG-2021#6]
делаем

**Comment by DmitriySosnovskiy** [comment]
сделали?

**Comment by GandhiKK** [comment]
нет

**Comment by DmitriySosnovskiy** [comment]
а когда 
![image](https://user-images.githubusercontent.com/45599375/116628511-f6a21b80-a957-11eb-804a-30ed9860d8ea.png)

**Comment by GandhiKK** [comment]
![image](https://user-images.githubusercontent.com/42946613/116628642-35d06c80-a958-11eb-9810-871c032e642e.png)

**Comment by GandhiKK** [comment]
![image](https://user-images.githubusercontent.com/42946613/116628650-3ec13e00-a958-11eb-8e4a-336e650e79a2.png)

**Comment by DmitriySosnovskiy** [comment]
а сейчас сделали?

**Comment by GandhiKK** [comment]
![Uploading dim1.png…]()

**Comment by GandhiKK** [comment]
![dim1](https://user-images.githubusercontent.com/42946613/117344386-01a40100-aeae-11eb-8519-37905588cb9b.png)

**Comment by DmitriySosnovskiy** [comment]
![image](https://user-images.githubusercontent.com/45599375/117344530-24361a00-aeae-11eb-90c8-efc1cf1dc009.png)
